# Generated by Django 3.2.4 on 2021-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=150)),
                ('unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Credit_card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=150)),
                ('card_signature', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('bin', models.CharField(max_length=6)),
                ('card_last_four_digit', models.CharField(max_length=4)),
                ('authorization_code', models.CharField(max_length=100)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('card_type', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=150)),
                ('payment_reference', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('save_card', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_code', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('tracking_ref', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
