# Generated by Django 3.0 on 2021-08-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210816_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card_details',
            name='account_name',
            field=models.CharField(default='invalid iccount name', max_length=100, null=True),
        ),
    ]
